### ISSUE TITLE
background: url is not working in component's README.md.

### ISSUE THREAD

**Issue by bfwg** [FIEOSA/webcomponent-mdl#1]
In `/src/card/README.md

``` css
  .demo-card-wide mdl-card-title {
    color: #fff;
    height: 176px;
    background: url('http://www.daisuki.net/content/dam/pim/daisuki/en/ONEPUNCHMAN/12550/movie.jpg');
  }
```

<img width="353" alt="screen shot 2016-10-22 at 12 40 35 pm" src="https://cloud.githubusercontent.com/assets/12819525/19622033/e1ca1014-9854-11e6-9400-2c3b6a51fb2d.png">

**Might be somthing wrong with gulp markdown.**
